name: Automation deployment

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'debug' 
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:

    runs-on: macos-latest
    
    env:
      NODE_ENV: 'qa'
      TEST_ENVIRONMENT: 'qa'
      BASE_URL: 'app://./index.html'
      PROJECT: 'nameproject'
      BROWSER: 'chrome'
      AdminUser: 'Aletesting1234!'
      AdminUserPassword: 'Change1234!'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
