# github action name
name: Automation deployment

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'debug' 
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: 'Dev'

jobs:
  build:
    runs-on: macos-latest
    if: $ENVIRONMENT == 'PROD'
    env:
      LEVEL: ${{ github.event.inputs.logLevel }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - name: Git checkout branch
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Installing Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build app
        run: |
          npm install
          npm run build
          cd dist
          ls
          
      - name: Run Automation
        run: |
          id
          id -un
          sudo lsof -PiTCP -sTCP:LISTEN
          npm run wdiots
