# github action name
name: Automation deployment

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'debug' 
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Git checkout branch
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Installing Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Download chrome driver
        uses: nanasess/setup-chromedriver@master

      - name: Launch chrome driver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Build app
        run: |
          npm install
          npm run build
          cd dist
          ls
          
      - name: Run Automation
        run: 
          sudo lsof -PiTCP -sTCP:LISTEN
          npm run wdiots
